---
- name: edit ansible.cfg
  hosts: localhost
  gather_facts: false
  ignore_errors: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: edit ansible.cfg
      blockinfile:
        path: /etc/ansible/ansible.cfg
        block: |
          [defaults]
          remote_user = team1
          private_key_file = ~/.ssh/id_rsa
          host_key_checking = False

          [privilege_escalation]
          become = True
          become_method = sudo
          become_user = root
