---
- name: create inventory file
  hosts: localhost
  gather_facts: false
  ignore_errors: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: inventory
      blockinfile:
        path: /etc/ansible/hosts
        create: yes
        block: |
          [controller]
          10.0.0.4

          [hosts]
          10.0.2.4
          10.0.3.4
          10.0.4.4
          10.0.6.4

          [web1]
          10.0.2.4

          [web2]
          10.0.3.4

          [ftp]
          10.0.4.4

          [autosc]
          10.0.5.[4:16]
